[[pages]]
path = "streamlit_app/home.py"
name = "ä¸»é¡µ"
icon = "ğŸ¡"

[[pages]]
path = "streamlit_app/pages/gpt_setting.py"
name = "æ¨¡å‹ç®¡ç†"
icon = "ğŸ¤–"

[[pages]]
path = "streamlit_app/pages/prompt.py"
name = "æç¤ºè¯ç®¡ç†"
icon = "ğŸ“"

[[pages]]
path = "streamlit_app/pages/plugins.py"
name = "æ’ä»¶ç®¡ç†"
icon = "ğŸ‘ğŸ»"